add motivation and reorder tutorials page
AIAScience/mflux-ai-tutorials pull request #33
Opened 2019-10-03 13:08 UTC by ErlendHov82

2019-10-03 13:20 UTC, iver56 requested changes

2019-10-03 13:20 UTC, iver56 commented on document-classification/content.md
> -`mlflow.keras.autolog()` performs one HTTP request against the MLflow server after each epoch,
Uh-oh, it looks like you are accidentally reverting a change I did earlier

2019-10-03 13:20 UTC, iver56 commented on log-batch/content.md
> -call. This limit is typically 1000. If you exceed the limit, you'll get an error like this:
Uh-oh, it looks like you are accidentally reverting a change I did earlier

2019-10-04 07:25 UTC, ojsvendsli commented on boston-crime-forecasting/content.md
> +This tutorial shows something close to a real data science project. It is more complicated than most other tutorials on
This tutorial shows a small data science project.

2019-10-04 07:28 UTC, ojsvendsli commented on document-classification/content.md
> +By classifying documents, we are aiming to assign one or more classes or categories to a document, making it easier to
By classifying documents, we are assigning one or more classes or categories to a document

2019-10-04 11:28 UTC, iver56 commented
Closed because https://github.com/AIAScience/mflux-ai-tutorials/pull/34 took over

2019-10-04 11:28 UTC, closed without merging